const STRIPE_CONFIG = {
  PUBLISHABLE_KEY: "pk_test_51T6M8fLOOvSokDIXRLmd8rOFVlIo9ch5UD4r5Cq3PpGIZY41BCNzWywzWSmWBPEocTkKe1BeJjKsG9ZNe09EEuLA00XYO1a0la",

  MERCHANT_NAME: "UCSB Rideshare",
};

export default STRIPE_CONFIG;